apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-generic
  annotations:
    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/on-event: "push"
spec:
  params:
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: all_changed_files
      value: "{{ all_changed_files }}"
    - name: added_files
      value: "{{ added_files }}"
    - name: deleted_files
      value: "{{ deleted_files }}"
    - name: modified_files
      value: "{{ modified_files }}"
    - name: renamed_files
      value: "{{ renamed_files }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: all_changed_files
      - name: added_files
      - name: deleted_files
      - name: modified_files
      - name: renamed_files
    workspaces:
      - name: source
      - name: basic-auth
    tasks:
      - name: noop-task
        displayName: Task with no effect
        params:
          - name: all_changed_files
            value: $(params.all_changed_files)
          - name: added_files
            value: $(params.added_files)
          - name: deleted_files
            value: $(params.deleted_files)
          - name: modified_files
            value: $(params.modified_files)
          - name: renamed_files
            value: $(params.renamed_files)
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              workingDir: $(workspaces.source.path)
              script: |
                exit 0
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  # This workspace will inject secret to help the git-clone task to be able to
  # checkout the private repositories
  - name: basic-auth
    secret:
      secretName: "{{ git_auth_secret }}"