apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-push
  annotations:
    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-cel-expression: >-
      ( event == "push" &&  target_branch == "main" ) &&
      ( files.all.exists(x, x.matches('.tekton/pullrequest.yaml')) || files.all.exists(x, x.matches('modified.txt')) )
spec:
  pipelineSpec:
    tasks:
      - name: changed-files-push-params
        taskSpec:
          steps:
            - name: test-changed-files-params-push
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                # reply Should be:
                cat <<EOF
                changed files...
                files.all: {{ files.all }}
                files.added: {{ files.added }}
                files.deleted: {{ files.deleted }}
                files.modified: {{ files.modified }}
                files.renamed: {{ files.renamed }}

                EOF